/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_AWS_ACCESS_KEY_ID: process.env.NEXT_AWS_ACCESS_KEY_ID,
    NEXT_AWS_SECRET_ACCESS_KEY: process.env.NEXT_AWS_SECRET_ACCESS_KEY,
    NEXT_AWS_REGION: process.env.NEXT_AWS_REGION,
    NEXT_AWS_BUCKET_NAME: process.env.NEXT_AWS_BUCKET_NAME,
    NEXT_AWS_BUCKET_DOWNLOAD_NAME: process.env.NEXT_AWS_BUCKET_DOWNLOAD_NAME,
    NEXT_AWS_DYNAMODB_TABLE_NAME: process.env.NEXT_AWS_DYNAMODB_TABLE_NAME,
    NEXT_AWS_DYNAMODB_UPLOAD_PROGRESS_TABLE_NAME: process.env.NEXT_AWS_DYNAMODB_UPLOAD_PROGRESS_TABLE_NAME,
    NEXT_AWS_DYNAMODB_DOWNLOAD_TABLE_NAME: process.env.NEXT_AWS_DYNAMODB_DOWNLOAD_TABLE_NAME,
  }
}

module.exports = nextConfig
