import getCurrentUser from '@/actions/getCurrentUser'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LoginModal from '@/components/modals/LoginModal'
import { MainNav } from '@/components/MainNav'
import { UserNav } from '@/components/UserNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentuser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginModal />
        <div className="flex-col md:flex">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <MainNav className="mx-6" currentuser={currentuser} />
              <div className="ml-auto mr-4 flex items-center space-x-4">
                <UserNav currentuser={currentuser} />
              </div>
            </div>
          </div>
          <div className="w-full flex-1 space-y-4 p-8 pt-6">
            <div className="h-full ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
